// ======================================
// File declares ACTION TYPES as constants
// ======================================


// Searching for a player

export const DEFINE_SEARCH_TERM = "DEFINE_SEARCH_TERM";
export const SET_THISWEEK_EVERYONE_TOGGLE = "SET_THISWEEK_EVERYONE_TOGGLE";
export const CLUB_DATA_LOADED = "CLUB_DATA_LOADED";
export const PLAYER_DATA_LOADED = "PLAYER_DATA_LOADED";
export const PLAYER_DATA_LOADED_EVERYONE = "PLAYER_DATA_LOADED_EVERYONE";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const SET_PLAYER = "SET_PLAYER";
export const SET_CLUB = "SET_CLUB";
export const SET_AGREE_DISAGREE_SCORES = "SET_AGREE_DISAGREE_SCORES";
export const SET_CLUB_AGREE_DISAGREE_SCORES = "SET_CLUB_AGREE_DISAGREE_SCORES";
export const AGREE_DISAGREE_LOCAL_UPDATE = "AGREE_DISAGREE_LOCAL_UPDATE";
export const AGREE_DISAGREE_LOCAL_UPDATE_CLUBS = "AGREE_DISAGREE_LOCAL_UPDATE_CLUBS";


// Insights actions 
export const SET_GRID_CARD_VIEW = "SET_GRID_CARD_VIEW";
export const SET_INSIGHTS_CATEGORY = "SET_INSIGHTS_CATEGORY";
export const SET_TOP_BOTTOM_INSIGHTS = "SET_TOP_BOTTOM_INSIGHTS";
export const GET_PLAYER_REVIEW_SCORES = "GET_PLAYER_REVIEW_SCORES";
export const CLEAR_PLAYER_REVIEW_SCORES = "CLEAR_PLAYER_REVIEW_SCORES";
export const GET_PLAYER_TOTAL_REVIEWS = "GET_PLAYER_TOTAL_REVIEWS";
export const GET_PLAYER_AVG_SCORE = "GET_PLAYER_AVG_SCORE";
export const SET_FILTER_ACTIVE_STATE = "SET_FILTER_ACTIVE_STATE";


// Filter actions
export const ADD_POSITION_FILTER = "ADD_POSITION_FILTER";
export const REMOVE_POSITION_FILTER = "REMOVE_POSITION_FILTER";
export const ADD_CLUB_FILTER = "ADD_CLUB_FILTER";
export const REMOVE_CLUB_FILTER = "REMOVE_CLUB_FILTER";
export const ADD_NATIONALITY_FILTER = "ADD_NATIONALITY_FILTER";
export const REMOVE_NATIONALITY_FILTER = "REMOVE_NATIONALITY_FILTER";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";
export const APPLY_REVIEW_SCORE_FILTER = "APPLY_REVIEW_SCORE_FILTER";
export const APPLY_TOTAL_SCORES_FILTER = "APPLY_TOTAL_SCORES_FILTER";
export const APPLY_AVG_SCORES_FILTER = "APPLY_AVG_SCORES_FILTER";


// Blog actions
export const GET_BLOGPOST_LIST = "GET_BLOGPOST_LIST";

// Other actions
export const GET_SOURCES_LIST = "GET_SOURCES_LIST";
export const CLEAR_SOURCES_LIST = "CLEAR_SOURCES_LIST";
export const GET_ARRAY_CRAWL_DATES = "GET_ARRAY_CRAWL_DATES";
export const SET_ERROR_STATUS = "SET_ERROR_STATUS";