# Generated by Django 3.0.7 on 2020-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200618_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('media_source', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=300)),
                ('sentiment', models.CharField(max_length=50)),
                ('original_sentence', models.TextField()),
            ],
            options={
                'ordering': ['date', 'player', 'sentiment', 'media_source', 'url', 'sentiment', 'original_sentence'],
            },
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(),
        ),
    ]
