# Generated by Django 3.0.7 on 2020-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200625_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=150)),
                ('club', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['player', 'club', 'position', 'nationality'],
            },
        ),
    ]
