# Generated by Django 3.0.7 on 2020-06-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player'),
        ),
    ]
