# Generated by Django 3.0.7 on 2020-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200625_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['date', 'player_name', 'sentiment_score']},
        ),
        migrations.AddField(
            model_name='score',
            name='player_name',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='player_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
