# Generated by Django 3.0.7 on 2020-06-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200625_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['date', 'player_name', 'sentiment', 'media_source', 'url', 'sentiment', 'original_sentence']},
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='player',
        ),
    ]
