# Generated by Django 3.0.7 on 2020-06-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200625_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Player'),
            preserve_default=False,
        ),
    ]
