# Generated by Django 3.0.7 on 2020-06-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sentence_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main.Player'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='main.Player'),
        ),
    ]
