# Generated by Django 3.0.7 on 2020-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200625_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['club'],
            },
        ),
        migrations.CreateModel(
            name='ClubScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('sentiment_score', models.FloatField()),
                ('n_positive', models.IntegerField()),
                ('n_negative', models.IntegerField()),
                ('n_neutral', models.IntegerField()),
                ('total_reviews', models.IntegerField()),
            ],
            options={
                'ordering': ['date', 'club_name', 'sentiment_score'],
            },
        ),
        migrations.CreateModel(
            name='ClubSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('media_source', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=300)),
                ('sentiment', models.CharField(max_length=50)),
                ('original_sentence', models.TextField()),
            ],
            options={
                'ordering': ['date', 'club_name', 'sentiment', 'media_source', 'url', 'sentiment', 'original_sentence'],
            },
        ),
    ]
