# Generated by Django 3.0.7 on 2020-06-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200626_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['player', 'club_name', 'position', 'nationality']},
        ),
        migrations.AddField(
            model_name='player',
            name='club_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.Club'),
        ),
    ]
