# Generated by Django 3.0.7 on 2020-06-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200626_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
    ]
