# Generated by Django 3.0.7 on 2020-06-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_player_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.Club'),
            preserve_default=False,
        ),
    ]
