# Generated by Django 3.0.7 on 2020-07-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_player_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('date_visited', models.DateField()),
            ],
            options={
                'ordering': ['date_visited', 'url'],
            },
        ),
    ]
