# Generated by Django 3.0.7 on 2020-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_clubagreedisagree_playeragreedisagree'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.TextField()),
                ('header_image_url', models.URLField(max_length=500)),
                ('headline', models.CharField(max_length=300)),
                ('thumbs_par', models.TextField()),
                ('crawl_date', models.DateField()),
                ('player_one_name', models.CharField(max_length=300)),
                ('player_two_name', models.CharField(max_length=300)),
                ('player_three_name', models.CharField(max_length=300)),
                ('player_four_name', models.CharField(max_length=300)),
                ('club_one_name', models.CharField(max_length=300)),
                ('club_two_name', models.CharField(max_length=300)),
                ('date_text', models.CharField(max_length=150)),
                ('par_one', models.TextField()),
                ('par_two', models.TextField()),
                ('par_three', models.TextField()),
                ('par_four', models.TextField()),
                ('par_five', models.TextField()),
                ('par_six', models.TextField()),
                ('par_seven', models.TextField()),
                ('par_eight', models.TextField()),
                ('pull_quote_one', models.TextField()),
                ('pull_quote_two', models.TextField()),
                ('pull_quote_three', models.TextField()),
            ],
            options={
                'ordering': ['date_text', 'headline'],
            },
        ),
    ]
