# Generated by Django 3.0.7 on 2020-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='player_one_rank',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='player_three_rank',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='player_two_rank',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
